### ISSUE TITLE
Elixir not in PATH

### ISSUE THREAD

**Issue by ph-One** [amkirsch/chef-cookbook-phoenix#1]
the Elixir binaries are not in PATH.
`PATH=$PATH:/opt/elixir/bin`

**Comment by amkirsch** [comment]
Thanks for pointing this out @ph-One !  Adding this to the install process, I am currently testing changes.

**Comment by amkirsch** [comment]
This issue should now be fixed.  Also added step to ensure Erlang is always in the PATH.  Please let me know if you have further issues.  Thanks!
