### ISSUE TITLE
Feature Request: Add NodeJS as flag when running cookbook

### ISSUE THREAD

**Issue by ph-One** [amkirsch/chef-cookbook-phoenix#2]
Not sure how Chef handles this, but at the time of running the cookbook, can we specify whether or not we want NodeJS installed?

**Comment by ph-One** [comment]
```
curl -LO https://nodejs.org/dist/v6.2.0/node-v6.2.0-linux-x64.tar.xz
tar xf node-v6.2.0-linux-x64.tar.xz 
mv node-v6.2.0-linux-x64 nodejs
export PATH=$PATH:/nodejs/bin
```

**Comment by amkirsch** [comment]
Yes, this can be done easily enough.  I can create a flag to install NodeJS optionally, likely defaulting to false unless the consensus is it's expected to come with Phoenix?  Thank you for providing the basic steps. Definitely speeds things up!

Not sure when I'll have time to do this but it's now on my radar.

**Comment by amkirsch** [comment]
Per tag v1.2 this feature request has been fulfilled.  The cookbook is able to install NodeJS v6.2.0 optionally, simply add the new recipe "install_nodejs" to your role/runlist.  Closing Issue#2
